<a href="https://colab.research.google.com/github/sanu00007/Deep_Learning/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import torch

In [10]:
 import torch
 import numpy as np

**LISTS**

In [6]:

my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY ARRAYS**


In [12]:
np1 = np.random.rand(3,4)
np1

array([[0.33728833, 0.48661897, 0.47482718, 0.99916339],
       [0.23757794, 0.54519405, 0.90884213, 0.31037147],
       [0.24621946, 0.72982685, 0.70665934, 0.06672612]])

**TENSORS**

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[ 0.1369, -0.0882, -1.3727,  0.2648],
        [ 1.1970,  0.6853, -0.6926,  1.0481],
        [-0.6726, -0.9491, -0.6669, -0.0721]])

In [14]:
tenser_3d = torch.zeros(2,3,4)
tenser_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3373, 0.4866, 0.4748, 0.9992],
        [0.2376, 0.5452, 0.9088, 0.3104],
        [0.2462, 0.7298, 0.7067, 0.0667]], dtype=torch.float64)

****

In [17]:
my_torch = torch.arange(10)
my_torch


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
#reshape if we dont know the number of item

In [21]:
my_torch2 = torch.arange(10)

In [23]:
my_torch2 = my_torch2.reshape(-1,5) #or(5,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
#view

In [25]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_torch4 = my_torch3.view(-1,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5 = torch.arange(10)

In [29]:
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
my_torch5[1] = 4141

In [32]:
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [33]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [36]:
#slices
my_torch7 =  torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#grab a specific item
my_torch7[7]
#grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [41]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [42]:
#to keep shape //column
my_torch8[:,1:]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**MATH OPERATIONS IN TORCH**

In [43]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [52]:
#addition
tensor_a + tensor_b

#addition long hand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [53]:
#substraction
tensor_a - tensor_b

#substraction long hand
torch.sub(tensor_a,tensor_b)


tensor([-4, -4, -4, -4])

In [54]:
#multiplicaion
tensor_a * tensor_b

#multiplicaion long hand
torch.mul(tensor_a,tensor_b)


tensor([ 5, 12, 21, 32])

In [55]:
#division
tensor_a / tensor_b

#division long hand
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [60]:
#remainder
tensor_a % tensor_b
#remainder long hand
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

In [61]:
#exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [72]:
tensor_a = tensor_a + tensor_b
tensor_a
#another way to write long hand
#reassigned value of a to a+b
tensor_a.add(tensor_b)


tensor([31, 38, 45, 52])

In [75]:
torch.add(tensor_a,tensor_b)



tensor([31, 38, 45, 52])